package main

import (
	"log"

	"todo-apps/config"

	"github.com/joho/godotenv"
)

func main() {
	// Load environment variables
	if err := godotenv.Load(); err != nil {
		log.Println("Warning: .env file not found, using default values")
	}

	// Initialize database connection
	cfg := config.NewConfig()

	// Enable UUID extension in PostgreSQL
	err := cfg.Database.Exec("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"").Error
	if err != nil {
		log.Println("Warning: Could not enable uuid-ossp extension:", err)
		log.Println("UUIDs will be generated by the application instead of database")
	}
}
