package main

import (
	"log"
	"os"

	"todo-apps/config"
	"todo-apps/handlers"
	"todo-apps/middleware"
	"todo-apps/models"
	"todo-apps/services"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/joho/godotenv"
)

func main() {
	// Load environment variables
	if err := godotenv.Load(); err != nil {
		log.Println("Warning: .env file not found, using default values")
	}

	// Initialize database connection
	cfg := config.NewConfig()

	// Enable UUID extension in PostgreSQL
	err := cfg.Database.Exec("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"").Error
	if err != nil {
		log.Println("Warning: Could not enable uuid-ossp extension:", err)
		log.Println("UUIDs will be generated by the application instead of database")
	}

	// Initialize MongoDB connection
	mongodb := config.NewMongoDB()
	defer mongodb.Disconnect()

	// Auto-migrate database schemas
	err = cfg.Database.AutoMigrate(
		&models.User{},
		&models.Task{},
		&models.Position{},
		&models.UserPosition{},
	)
	if err != nil {
		log.Fatal("Failed to migrate database:", err)
	}

	// Initialize services
	auditService := services.NewAuditService(mongodb)

	// Initialize handlers
	authHandler := handlers.NewAuthHandler(cfg)
	userHandler := handlers.NewUserHandler(cfg, auditService)

	// Initialize Fiber app
	app := fiber.New(fiber.Config{
		ErrorHandler: func(c *fiber.Ctx, err error) error {
			code := fiber.StatusInternalServerError
			if e, ok := err.(*fiber.Error); ok {
				code = e.Code
			}
			return c.Status(code).JSON(fiber.Map{
				"error": err.Error(),
			})
		},
	})

	// Middleware
	app.Use(logger.New())
	app.Use(recover.New())
	app.Use(cors.New())

	// Public routes
	auth := app.Group("/auth")
	auth.Post("/login", authHandler.Login)
	auth.Post("/register", authHandler.Register)

	// Protected routes
	api := app.Group("/api")
	api.Use(middleware.JWTMiddleware())

	// User routes
	users := api.Group("/users")
	users.Get("/", userHandler.GetUsers)
	users.Post("/", userHandler.CreateUser)
	users.Put("/:id", userHandler.UpdateUser)
	users.Delete("/:id", userHandler.DeleteUser)

	// Start server
	port := os.Getenv("PORT")
	if port == "" {
		port = "3000"
	}

	log.Printf("Server starting on port %s...", port)
	log.Fatal(app.Listen(":" + port))

}
